Feature/reset password
CECS-491A/SSO pull request #31
Opened 2019-03-12 00:01 UTC by WinnMoo

# Issue/Ticket

PROGRESS ON: Frontend for reset password

# Description

Adds frontend code for resetting password, and updating password. Properly sends emails now. Reset controller responds correctly to requests.

## Type of change

Feature

# How Has This Been Tested?

Reset controller has been tested with postman
Frontend views have been manually tested

2019-03-12 08:25 UTC, alfredovargasjr requested changes

2019-03-12 08:25 UTC, alfredovargasjr commented on Backend/DataAccessLayer/DataAccessLayer.csproj
>      <Reference Include="System.ComponentModel.DataAnnotations" />
Seems like this PR is not up to date with master

2019-03-13 01:45 UTC, julianpoy requested changes

2019-03-13 01:45 UTC, julianpoy commented on Backend/DataAccessLayer/DataAccessLayer.csproj
> +  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
Why is this whole file modified? Please revert this and make only the changes you need.

2019-03-13 01:45 UTC, julianpoy commented on Backend/DataAccessLayer/Database/dbContext.cs
> +}
Same with this file - why is the whole file modified? Make the changes you need and leave the rest the same.

2019-03-13 01:45 UTC, julianpoy commented on Backend/DataAccessLayer/Migrations/201903070039162_create-tables-applications-apikeys.cs
> +}
Same comment here

2019-03-13 01:45 UTC, julianpoy commented on Backend/DataAccessLayer/Migrations/201903090835106_create-table-passwordreset.cs
>  }
This migration really shouldn't be modified. A new migration should be created that changes the name of that column and updates the primary key.

2019-03-13 01:45 UTC, julianpoy commented on Backend/DataAccessLayer/Migrations/201903090835106_create-table-passwordreset.cs
>  }
Remember, migrations are like git history. We try not to modify them since it'll break everyone elses databases.

2019-03-13 01:45 UTC, julianpoy commented on Backend/DataAccessLayer/Migrations/201903100743056_create-attribute-incorrectPasswordCount.cs
> +}
Same comments here... I'm going to stop commenting on this. Fix them all.

2019-03-13 01:46 UTC, julianpoy commented
This PR has an enormous number of modified files - make sure to only modify the files you need to, and make sure to only modify the lines you need to within. Visual Studio may automatically modify many files, but that doesn't mean you should commit those modifications.

2019-03-14 01:07 UTC, closed without merging