Updated frontend Code. It now uses vuetify, and localstorage. Added l…
CECS-491A/SSO pull request #42
Opened 2019-03-16 07:17 UTC by cf2080

# Issue/Ticket

CLOSES #XX

# Description
Updated frontend Code. It now uses vuetify, and local storage. Added link to reset password page

## Type of change
Chore

Label your PR accordingly.
manually tested

2019-03-16 16:35 UTC, julianpoy commented on Backend/DataAccessLayer/Repositories/ApiKeyRepository.cs
> +        /// <summary>
This should not be changed.

2019-03-16 16:36 UTC, julianpoy commented on Frontend/src/const.js
> +    DEV_ROUTE: dev_route
Don't revert this file. These need to come from env variables, so either make that change or leave as-is for merge.

2019-03-16 16:36 UTC, julianpoy commented on Frontend/src/main.js
> +  axios,
Why this change?

2019-03-16 16:37 UTC, julianpoy commented on Frontend/src/services/request.js
> +      token = response.data.data.token;
None of these changes should be present. These are all reversions of the changes I made in my branch.

2019-03-16 16:38 UTC, julianpoy commented on Frontend/src/views/Register.vue
>              this.error = "Your email address does not follow a recognized format.";
Again, you're changing registration. This should not be changed.

2019-03-16 16:38 UTC, julianpoy requested changes
See my comments. Also, the comments I made in your other PR apply here.

2019-03-16 22:43 UTC, alfredovargasjr commented
@cf2080 make this also has the latest changes

2019-03-17 17:06 UTC, julianpoy commented on Frontend/src/views/Register.vue
> -
This file should not be changed in this PR.

2019-03-17 17:43 UTC, julianpoy approved these changes

2019-03-17 17:54 UTC, merged