updated some failed test and cleaned some code, changes to UI as well
CECS-491A/SSO pull request #50
Opened 2019-03-18 07:14 UTC by alfredovargasjr

# Issue/Ticket

CLOSES #XX
PROGRESS ON #XX

If you specify CLOSES, the ticket will be automatically closed and moved to 'done' when the PR is merged.

If you specify PROGRESS ON, a reference will be created to that issue (in both directions), but merging the PR will not close the issue.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

List one of the following: Bug (Fix), Feature, Chore

Label your PR accordingly.

# How Has This Been Tested?

Please describe and list the tests that you wrote for each module changed. If there are any special considerations, mention them here.

- Test A
- Test B

# Notes

Put any notes here

2019-03-22 16:00 UTC, alfredovargasjr commented
Need this to be reviewed

2019-03-24 23:13 UTC, julianpoy requested changes

2019-03-24 23:13 UTC, julianpoy commented on Backend/DataAccessLayer/App.config
> -  </entityFramework>
Why was this file modified?

2019-03-25 05:15 UTC, alfredovargasjr commented on Backend/DataAccessLayer/App.config
> -  </entityFramework>
Its not needed and duplicates

2019-03-26 00:21 UTC, julianpoy approved these changes

2019-03-26 00:21 UTC, merged