E2E screenshot tests
CECS-491A/SSO pull request #54
Opened 2019-03-21 01:27 UTC by krystalleon

# Issue/Ticket

CLOSES #XX

If you specify CLOSES, the ticket will be automatically closed and moved to 'done' when the PR is merged.

If you specify PROGRESS ON, a reference will be created to that issue (in both directions), but merging the PR will not close the issue.

# Description

Screenshot E2E testing with puppeteer for auto-app-sync feature

## Type of change

Chore

Label your PR accordingly.

# How Has This Been Tested?

# Notes

2019-03-22 19:28 UTC, alfredovargasjr commented
Do we want to add these test results to the repo?

2019-03-22 19:29 UTC, alfredovargasjr requested changes

2019-03-22 19:29 UTC, alfredovargasjr commented on E2E/Auto App Sync/ScreenshotTest.js
> +const puppeteer = require ('puppeteer');
You can leave this in the PR but I dont think we need the png files of the results.

2019-03-22 19:40 UTC, alfredovargasjr submitted a review, later dismissed

2019-03-22 19:40 UTC, alfredovargasjr commented on Backend/UnitTesting/SessionServiceUT.cs
> +        //[TestMethod]
Oh these test updates still need to be added to the master branch, :/

2019-03-22 19:40 UTC, alfredovargasjr commented on Backend/UnitTesting/SessionServiceUT.cs
> +        //[TestMethod]
For now, remove these changes from your PR, sorry

2019-03-24 23:22 UTC, julianpoy approved these changes
Looks good. We can develop this framework further, but thanks for posting a scaffold.

2019-03-24 23:45 UTC, merged