Added route to receive delete requests from individual apps. Needed t…
CECS-491A/SSO pull request #83
Opened 2019-04-10 07:28 UTC by andrewsoth

…o add signature validation methods within TokenService.

# Issue/Ticket

CLOSES #12 

If you specify CLOSES, the ticket will be automatically closed and moved to 'done' when the PR is merged.

If you specify PROGRESS ON, a reference will be created to that issue (in both directions), but merging the PR will not close the issue.

# Description

Added route to handle incoming delete requests from individual applications.

## Type of change

List one of the following: Feature

Label your PR accordingly.

# How Has This Been Tested?

Please describe and list the tests that you wrote for each module changed. If there are any special considerations, mention them here.

- Test A
- Test B

# Notes

Put any notes here

2019-04-10 21:50 UTC, alfredovargasjr requested changes

2019-04-10 21:50 UTC, alfredovargasjr commented on Backend/ServiceLayer/Services/TokenService.cs
> +        public string GenerateSignature(string plaintext, Application app)
Should this plaintext parameter be strongly typed? Like will signing always use the same values as part of the plaint text? Using just a string then anyone can set the plaintext as any combination of values. Just for thought, what you think

2019-04-10 22:36 UTC, andrewsoth commented
I made that for internal use to make sure requests are coming from our
apps. noone should be tampering with it. It should just be passing in
plaintext from incoming requests that have a PresignatureString which is
already  string type, so yeah it should continue to use the same values of
whatever PresignatureString is. Not sure if that's what you were asking?

On Wednesday, April 10, 2019, Alfredo Vargas <notifications@github.com>
wrote:

> *@alfredovargasjr* requested changes on this pull request.
> ------------------------------
>
> In Backend/ServiceLayer/Services/TokenService.cs
> <https://github.com/CECS-491A/SSO/pull/83#discussion_r274178611>:
>
> > @@ -17,5 +18,13 @@ public string GenerateToken()
>              string hex = BitConverter.ToString(b).Replace("-", "");
>              return hex;
>          }
> +
> +        public string GenerateSignature(string plaintext, Application app)
>
> Should this plaintext parameter be strongly typed? Like will signing
> always use the same values as part of the plaint text? Using just a string
> then anyone can set the plaintext as any combination of values. Just for
> thought, what you think
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CECS-491A/SSO/pull/83#pullrequestreview-225237315>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVftlqaJmrF0Xk1qbwsz-M8GUhLR3lIcks5vfly2gaJpZM4cmTjc>
> .
>

2019-04-17 03:07 UTC, alfredovargasjr approved these changes

2019-04-17 03:08 UTC, merged